apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
spec:
  selector:
    app: microservice-deployment
  ports:
    - name: port
      protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer