apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-volume-claim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: kubernetes-volume-1
