apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-volume-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/Unnati_PV_dir"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: kubernetes-volume-claim-1
    namespace: "default"
